current code clean up
mateo-marinovic/web-shop-profico-academy pull request #2
Opened 2023-09-15 19:16 UTC by mateo-marinovic

2023-09-15 19:58 UTC, ilovric00 requested changes

2023-09-15 19:58 UTC, ilovric00 commented on src/app/item-info/[id]/page.tsx
> +    <>
unnecessary fragment tags

2023-09-15 19:58 UTC, ilovric00 commented on src/app/item-info/[id]/page.tsx
> +      <ItemCounter></ItemCounter>
This can be self closing component

2023-09-15 19:58 UTC, ilovric00 commented on src/app/products/page.tsx
> +    <>
unnecessary fragment tags

2023-09-15 19:58 UTC, ilovric00 commented on src/app/wish-list/page.tsx
> +    <>
unnecessary fragment tags

2023-09-15 19:58 UTC, ilovric00 commented on src/components/item-card/item-card.tsx
> +    <>
unnecessary fragment tags

2023-09-15 19:58 UTC, ilovric00 commented on src/components/item-list/item-list.tsx
> +    <>
unnecessary fragment tags

2023-09-15 19:58 UTC, ilovric00 commented on src/components/item-counter/item-counter.tsx
> +    <>
unnecessary fragment tags

2023-09-15 19:58 UTC, ilovric00 commented on src/components/item-list/item-list.tsx
> +  return (
blank space before

2023-09-15 19:58 UTC, ilovric00 commented on src/components/items-header/items-header.tsx
> +    <>
unnecessary fragment tags

2023-09-15 19:58 UTC, ilovric00 commented on src/components/items-header/items-header.tsx
> +"use client";
this doesn't need to be a client component

2023-09-15 19:58 UTC, ilovric00 commented on src/contexts/users.context.tsx
> +export function UsersProvider({ children }: UsersProviderProps) {
`export const UsersProvider: React.FC<PropsWithChildren> = ({ children }) => {...}`

2023-09-15 19:58 UTC, ilovric00 commented on src/types/product.ts
> +}
since this is an interface, a file should be located inside `src/interfaces/`

2023-09-22 19:40 UTC, mateo-marinovic commented
I added search bar and fixe PR comments. Also, I accidentally pushed new feature in the same branch. In the future will create new branches for the new features

2023-09-26 12:03 UTC, ilovric00 commented
Too huge PR

2023-09-26 12:09 UTC, ilovric00 approved these changes

2023-09-26 12:09 UTC, ilovric00 commented on src/components/items-header/items-header.tsx
> +    <Link href={"/wish-list"}>
`<Link href="/wish-list">`

2023-09-26 12:09 UTC, ilovric00 commented on src/components/item-list/item-list.tsx
> +    <ul className="">
empty className, remove it

2023-10-15 20:21 UTC, merged